# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "ko-KR"
title: "(주)도울정보기술"
title_separator: "-"
subtitle: # site tagline that appears below site title in masthead
name: "www.doulit.co.kr"
copyright: "DOULIT"
description: "(주)도울정보기술 홈페이지입니다."
keywords: "도울정보기술, 도울, doul, 정보, 기술, 정보화서비스, SI, 솔루션, 개발, 시스템구축, 유지보수, 기업 정보화 컨설팅,시스템 통합,웹개발,정보화 인프라 구축,IT관련 토탈서비스"
url: "http://doulit.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute: 200

# Site Info
tel: "051-646-0456"
fax: "051-645-0453"
email: "chitosoo@gmail.com"
address: "한일오피스텔 1915호"
full_address: "부산시 남구 자성로 152 한일오피스텔 1915호"
company_number: "617-81-56655"

# Site Author
author:
  name: "성기동"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Developer"
  location: "Busan"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# What we do
doings:
  [
    { name: "기업 정보화 컨설팅", image: "icon_data" },
    { name: "시스템 통합", image: "icon_system" },
    { name: "시스템 구축 및 유지보수", image: "icon_maintain" },
    { name: "WEB 개발", image: "icon_web" },
    { name: "정보화 인프라 구축", image: "icon_infra" },
    { name: "IT관련 Total Service 제공", image: "icon_total" },
  ]

# Partners
partners:
  [
    { id: "01", name: "부산대학교", image: "img_logo_bs" },
    { id: "02", name: "동의대학교", image: "img_logo_de" },
    { id: "03", name: "동의과학대학교", image: "img_logo_dit" },
    { id: "04", name: "광운대학교", image: "img_logo_kw" },
    { id: "05", name: "대우조선해양", image: "img_logo_dsme" },
    { id: "06", name: "동명대학교", image: "img_logo_tm" },
    { id: "07", name: "desc", image: "img_logo_dsec" },
    { id: "08", name: "동서대학교", image: "img_logo_dsu" },
    { id: "09", name: "계명대학교", image: "img_logo_km" },
    { id: "10", name: "중소조선연구원", image: "img_logo_rims" },
    { id: "11", name: "동아대학교", image: "img_logo_da" },
    { id: "12", name: "KRISO", image: "img_logo_kriso" },
    { id: "13", name: "계명문화대학교", image: "img_logo_kmm" },
    { id: "14", name: "부경대학교", image: "img_logo_bk" },
    { id: "15", name: "국립금오공과대학교", image: "img_logo_go" },
    { id: "16", name: "흥아포밍", image: "img_logo_ha" },
    { id: "17", name: "경남정보대학교", image: "img_logo_kit" },
    { id: "18", name: "고신대학교", image: "img_logo_ks" },
    { id: "19", name: "서울기독대학교", image: "img_logo_scu" },
    { id: "20", name: "TEIKURO", image: "img_logo_teikuro" },
  ]
